### ISSUE TITLE
i3lock-wrapper cannot specify --inactivity-timeout

### ISSUE THREAD

**Issue by woybi** [ashinkarov/i3-extras#27]
Hello,
I am having trouble in setting the "--inactivity-timeout" argument.
For exemple, when I type in my terminal:
`i3lock-wrapper -d --inactivity-timeout 10`
It return with zsh:
`i3lock-wrapper: invalid arguments "10"`

while
`i3lock -d --inactivity-timeout 10`
Works perfectly

**Comment by ashinkarov** [comment]
It should be `i3lock-wrapper -d --inactivity-timeout=10`, that is a common paradigm of getopt for passing values to long options.  That is one use `-shortopt x` and `-longopt=x`.

**Comment by woybi** [comment]
Thanks for replying so fastly.
I tried what you said:
`i3lock-wrapper -d --inactivity-timeout=10`
But it doesn't work neither, here is what I get:
`i3lock-wrapper : l'option « --inactivity-timeout » ne permet pas d'argument`
(traduction in english: the setting --inactivity-timeout does not allow argument)

**Comment by ashinkarov** [comment]
Oh!  Interesting, I found the problem.

The `i3lock-wrapper` does not allow the argument, because the manual of `i3lock` is a bit confusing.

It says:
```
       -I, --inactivity-timeout
              Specifies  the  number of seconds i3lock will wait for another password before turning
              off the monitors, in case you entered a wrong password or canceled by pressing Escape.
              Only makes sense together with -d. If omitted, the default is 30 seconds.
```
where it should say something like `-I min, --inactivity-timeout=min` like it does in other cases when parameters accept an argument.  I will fix the i3lock-wrapper shortly, and I would suggest to file a bug (or better a patch) to fix i3lock.

**Comment by ashinkarov** [comment]
Commit 9acf3cbcd9245a02d446b81b881922da220fc4ae should fix it.

**Comment by woybi** [comment]
Yep it's working, thank you!
